---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.web.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        component: web
      annotations:
        checksum/php-env-cm: {{ include (print $.Template.BasePath "/php-env-cm.yaml") . | sha256sum }}
        checksum/php-env-secret: {{ include (print $.Template.BasePath "/php-env-secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      {{- if .Values.php.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.php.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "app.php-env.name" . }}-shared
      containers:
        - name: web
          image: {{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}
          imagePullPolicy: IfNotPresent
          # Use sub-path for individual folders
          volumeMounts:
            - mountPath: /app/public/assets
              name: shared
              subPath: assets
            - mountPath: /app/system
              name: shared
              subPath: system
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 120
          envFrom:
            - configMapRef:
                name: {{ template "app.php-env.name" . }}
            - secretRef:
                name: {{ template "app.php-env.name" . }}
